spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    
  flyway:
    enabled: true
    clean-disabled: false



logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE

