ALTER TABLE users ADD COLUMN IF NOT EXISTS is_suspended BOOLEAN DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS suspension_reason varchar(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS suspendAt TIMESTAMP DEFAULT NULL;