CREATE TABLE IF NOT EXISTS order_status_history(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    order_id BIGINT,
    status VARCHAR(55),
    created_at TIMESTAMP DEFAULT NOW(),
    CONSTRAINT order_status_history_status_check
        CHECK(status IN ('COMPLETED', 'PENDING', 'PROCESSING', 'RECEIVE')),
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (order_id) REFERENCES orders (id)
);