CREATE TABLE refund_requests (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 approved_at TIMESTAMP,
                                 description TEXT,
                                 reason VARCHAR(255) NOT NULL,
                                 requested_at TIMESTAMP,
                                 status VARCHAR(255),
                                 order_id BIGINT,
                                 user_id BIGINT,
                                 CONSTRAINT refund_requests_status_check
                                     CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED'))
);

ALTER TABLE refund_requests
    ADD CONSTRAINT fk_refund_order
        FOREIGN KEY (order_id) REFERENCES orders(id);

ALTER TABLE refund_requests
    ADD CONSTRAINT fk_refund_user
        FOREIGN KEY (user_id) REFERENCES users(id);