CREATE TABLE IF NOT EXISTS refund_requests (
                                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               approved_at TIMESTAMP,
                                               description TEXT,
                                               reason VARCHAR(255) NOT NULL,
    requested_at TIMESTAMP,
    status VARCHAR(255),
    order_id BIGINT,
    user_id BIGINT,
    CONSTRAINT refund_requests_status_check
    CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED'))
    );